import { normalizedKey } from "./normalize";

/**
 * The icon an amenity is drawn with, as a slug rather than an asset.
 *
 * Resolved here and not in the web app for the same reason the group is: by the time a label
 * reaches the page it has been translated, and a Ukrainian one matches no table. The web app
 * owns what a slug looks like, this owns which amenity carries which slug, and the two meet on
 * a name the designer also files their SVG under.
 *
 * One slug serves several amenities wherever a charterer would not notice the difference --
 * every anchor is `anchor`, every distress signal is `flare` -- because a set of two hundred
 * near-identical icons costs a designer two hundred drawings and buys a reader nothing. What is
 * listed is roughly the equipment a boat in this catalogue actually carries; the rest falls back
 * to its group's own icon, which is true if unspecific.
 */
const AMENITY_ICONS = {
  /* Navigation and safety */
  autopilot: "autopilot",
  chartplotter: "chart-plotter",
  chartplotterincockpit: "chart-plotter",
  gps: "gps",
  radar: "radar",
  radarreflector: "radar",
  ais: "radar",
  compass: "compass",
  handbearingcompass: "compass",
  spyglasswithbearingcompass: "binoculars",
  maindeckcompass: "compass",
  binoculars: "binoculars",
  echosounderdepthsounder: "depth-sounder",
  depthsounder: "depth-sounder",
  logspeeddepthechosounder: "depth-sounder",
  tridata: "depth-sounder",
  windspeeddepthinstruments: "wind-instrument",
  windinstrumentanemometer: "wind-instrument",
  windex: "wind-instrument",
  speedometerspeedlog: "speed-log",
  logspeedinstrument: "speed-log",
  log: "speed-log",
  loggelotspeedwind: "speed-log",
  navigationnauticalchartsandnauticalguide: "charts",
  nauticalcharts: "charts",
  electronicseacharts: "charts",
  pilotbook: "charts",
  harbourguides: "charts",
  navigationset: "charts",
  completenavigationequipment: "charts",
  dividernauticchart: "plotting-tools",
  parallelruler: "plotting-tools",
  triangles: "plotting-tools",
  navigationpositionlights: "navigation-lights",
  helmstation: "helm",
  vhfradio: "vhf-radio",
  dscstation: "vhf-radio",
  epirbdistressradiobeacons: "epirb",
  liferaft: "liferaft",
  lifejackets: "life-jacket",
  lifejacketchildren: "life-jacket",
  automaticinflatablelifejacket: "life-jacket",
  selfinflatinglifevest: "life-jacket",
  lifebeltssafetyharness: "safety-harness",
  lifelines: "safety-harness",
  horseshoelifebuoy: "lifebuoy",
  lifebuoyflashinglight: "lifebuoy",
  floatinglight: "lifebuoy",
  distressflarebox: "flare",
  distresssignals: "flare",
  signalrocketsandtorches: "flare",
  buoyantsmokesignal: "flare",
  fireextinguisher: "fire-extinguisher",
  fireblanket: "fire-extinguisher",
  fireaxe: "fire-axe",
  firstaidkit: "first-aid",
  foghorn: "fog-horn",
  flashlight: "torch",
  torch: "torch",
  emergencytiller: "emergency-tiller",
  wireshroudcutter: "bolt-cutter",
  setoftools: "tools",
  repairkit: "tools",
  impellervbeltoilfilter: "tools",
  safetyequipment: "safety-kit",
  oarspaddles: "oars",
  bilgealarm: "bilge-alarm",

  /* Deck and cockpit */
  bimini: "bimini",
  sprayhood: "sprayhood",
  cockpitcushions: "cushions",
  outsidecushions: "cushions",
  sundeckcushions: "cushions",
  cockpittable: "cockpit-table",
  cockpittablewithlight: "cockpit-table",
  cockpitfridge: "cockpit-fridge",
  cockpitsternoutsideshower: "outside-shower",
  swimmingplatform: "swim-platform",
  tenderliftplatform: "swim-platform",
  swimmingladder: "swim-ladder",
  teakcockpit: "teak",
  teakdeck: "teak",
  dinghy: "dinghy",
  dinghybyboatpump: "dinghy-pump",
  repairboxfordinghy: "dinghy-pump",
  outboardengine: "outboard-engine",
  davit: "davit",
  gangway: "gangway",
  hydraulicgangway: "gangway",
  electricanchorwindlass: "windlass",
  anchor: "anchor",
  mainanchor: "anchor",
  anchorwithchain: "anchor",
  spareanchorreserveauxiliaryanchor: "anchor",
  anchordelta: "anchor",
  anchorswivel: "anchor",
  anchorline: "rope",
  mooringropes: "rope",
  springline: "rope",
  hawser: "rope",
  fenders: "fender",
  roundglobularfender: "fender",
  boathook: "boat-hook",
  winchhandles: "winch",
  winch: "winch",
  electricwinches: "winch",
  lazybag: "lazy-bag",
  lazyjack: "lazy-bag",
  gennaker: "sail",
  bosunschairsafeseatboatswainschair: "bosun-chair",
  waterhose: "water-hose",
  canisterforwater: "jerry-can",
  jerrycansfordiesel: "jerry-can",
  jerrycansforfuel: "jerry-can",
  fuelfunnel: "jerry-can",
  deckbrush: "deck-brush",
  sponge: "deck-brush",
  plasticbucket: "bucket",
  cockpitlight: "deck-light",
  spotlightheadlights: "deck-light",
  blackball: "day-shape",
  blackconus: "day-shape",
  flag: "flag",
  bilgepumpmechanic: "bilge-pump",
  flybridge: "flybridge",

  /* Interior and cabins */
  bedlinen: "bed-linen",
  bedlinenandtowels: "bed-linen",
  sheets: "bed-linen",
  pillows: "pillow",
  blankets: "blanket",
  towels: "towel",
  electrictoilet: "toilet",
  insideshower: "shower",
  electricfansincabins: "fan",
  electricfans: "fan",
  mosquitonets: "mosquito-net",
  convertibletable: "saloon-table",
  upholstery: "upholstery",
  clotheshangers: "hanger",
  barometer: "barometer",
  clock: "clock",
  yachtdocuments: "documents",
  washerdryer: "washer",

  /* Galley */
  refrigerator: "fridge",
  freezer: "freezer",
  icemaker: "ice-maker",
  oven: "oven",
  stove: "stove",
  gascookers: "stove",
  microwave: "microwave",
  dishwasher: "dishwasher",
  coffeemaker: "coffee-maker",
  mokapot: "coffee-maker",
  electricalkettle: "kettle",
  toaster: "toaster",
  sink: "sink",
  hotwater: "hot-water",
  pressurizedwatersystem: "water-pump",
  waterpump: "water-pump",
  kitchenutensilsgalleyequipmentcutlery: "cutlery",
  gasbottles: "gas-bottle",

  /* Entertainment and water toys */
  tv: "tv",
  dvdplayer: "tv",
  radiocdplayer: "radio",
  radio: "radio",
  cdplayer: "radio",
  radiomp3player: "radio",
  fusionradio: "radio",
  radiousbbluetooth: "radio",
  bluetoothplayer: "bluetooth",
  soundsystem: "sound-system",
  fusionsoundsystem: "sound-system",
  outdoorspeakers: "speaker",
  cockpitspeakers: "speaker",
  indoorspeakers: "speaker",
  underwaterlights: "underwater-light",
  snorkelingequipment: "snorkel",
  standuppaddle: "paddleboard",
  barbecuegrillincockpit: "barbecue",
  wifiandinternet: "wifi",
  swimmingpool: "pool",
  gameconsole: "game-console",

  /* Systems and power */
  aircondition: "air-conditioning",
  heating: "heating",
  generator: "generator",
  inverter: "inverter",
  solarpanels: "solar-panel",
  batteries: "battery",
  servicebatteries: "battery",
  startbattery: "battery",
  batterycharger: "battery-charger",
  shoreconnection220v: "shore-power",
  shorepowercable: "shore-power",
  shorepowerconnection: "shore-power",
  plug220v12v: "socket",
  "220vsocket": "socket",
  "110vsocket": "socket",
  "12vsocket": "socket",
  usb: "usb-socket",
  converter220v12v: "inverter",
  usbsockets: "usb-socket",
  watermaker: "water-maker",
  waterheater: "water-heater",
  holdingtank: "holding-tank",
  greywatertank: "holding-tank",
  bilgepumpelectric: "bilge-pump",
  pump: "water-pump",
  bowthruster: "bow-thruster",

  /* Added after measuring the catalogue: the long tail that still appears on thousands of boats. */
  spyglass: "binoculars",
  bretonplotter: "plotting-tools",
  lednavigationlights: "navigation-lights",
  inflatableliferaft: "liferaft",
  guardrail: "safety-harness",
  searchlight: "deck-light",
  compositesteeringwheels: "helm",
  listoflights: "charts",
  deckcushions: "cushions",
  sunmattresses: "cushions",
  teakseatsincockpit: "teak",
  sundeck: "sun-deck",
  sunshades: "sunshade",
  anchorchaincounter: "windlass",
  remotecontrolforanchorwinchwithchaincounterathelm: "windlass",
  bilgepumphandle: "bilge-pump",
  "3bladefoldingpropeller": "propeller",
  impeller: "tools",
  enginespareparts: "tools",
  reservemotoroil: "tools",
  toiletbrush: "cleaning",
  ledlights: "led-lights",
  ledinteriorlights: "led-lights",
  curtains: "curtains",
  safe: "safe",
  salontable: "saloon-table",
  duvetcover: "bed-linen",
  beachtowel: "towel",
  icebox: "cool-box",
  coolbox: "cool-box",
  coffeepot: "coffee-maker",
  dishes: "cutlery",
  radiowithusb: "radio",
  fins: "snorkel",
  fishingequipment: "fishing",
  decklights: "deck-light",
  spareparts: "tools",
  extrawatertank: "water-tank",
  hairdryer: "hair-dryer",
  gmdssglobalmaritimedistressandsafetysystem: "vhf-radio",
  selftailingmanualwinch: "winch",
  ambientallighting: "led-lights",
  indirectlightingincabinsandsalon: "led-lights",
  ropes: "rope",
  sternthruster: "bow-thruster",
  waterskis: "water-skis",
  selftackingjib: "sail",
  hifisystem: "sound-system",
  washingmachine: "washer",
  springcleats: "cleat",
  mooringcleats: "cleat",
  yachtkeys: "keys",
  lightandropeforhorseshoelifebuoy: "lifebuoy",
  signalflags: "flag",
  audiopack: "sound-system",
  wcpump: "toilet",
  blender: "blender",
  anchorwinchremotecontrol: "windlass",
  waterpurifier: "water-maker",
  screen: "tv",
} satisfies Record<string, string>;

/** The icon slug for an amenity, or null where the group's own icon has to stand in. */
export function amenityIconFor(label: string): string | null {
  return lookup(AMENITY_ICONS, normalizedKey(label));
}

/** The table read at a folded key, which is how it is written. */
function lookup(table: Record<string, string>, key: string): string | null {
  return table[key] ?? null;
}

/** Every slug in use, for the designer's brief and for the web app's coverage test. */
export function amenityIconSlugs(): string[] {
  return [...new Set(Object.values(AMENITY_ICONS))].sort();
}
