import type { ListingSearchDoc } from "@yacht-charter/db/search";

/** A priced search document for presenter and router tests. */
export const doc = (over: Partial<ListingSearchDoc> = {}): ListingSearchDoc => ({
  listingId: "ylst_1",
  slug: "liburna-sunseeker",
  name: "Liburna",
  title: "Liburna Sunseeker",
  category: "Motor yacht",
  crewType: "full_crew",
  builder: "Sunseeker",
  model: "Predator 60",
  modelCanonical: "Predator 60",
  operator: "Alimos Charter",
  operatorTermsAndConditions: null,
  baseId: "base_1",
  baseName: "Alimos Marina",
  city: "Athens",
  location: "Alimos",
  region: "Attica",
  country: "Greece",
  lat: null,
  lng: null,
  baseEmail: null,
  basePhone: null,
  baseWebsite: null,
  baseCheckInTime: "17:00",
  baseCheckOutTime: "09:00",
  lengthM: "15.50",
  cabins: 3,
  berths: 6,
  heads: 2,
  showers: 3,
  yearBuilt: 2023,
  sailType: null,
  securityDepositMinor: 310_000,
  securityDepositCurrency: "EUR",
  securityDepositWhenInsuredMinor: null,
  depositInsuranceIncluded: true,
  petsAllowed: false,
  bestValue: false,
  rating: "5.00",
  reviewCount: 4,
  bookedThisMonth: 0,
  viewedToday: 2,
  mainImage: null,
  gallery: [],
  amenities: [],
  bestOfferId: "loff_1",
  offerCount: 1,
  priceFromMinor: 1_240_000,
  priceIsFrom: false,
  listPriceFromMinor: null,
  currency: "EUR",
  priceFromMinorEur: 1_240_000,
  basePriceFromMinor: 1_000_000,
  basePriceFromMinorEur: 1_000_000,
  availableFrom: "2026-06-13",
  availableTo: "2026-08-29",
  bookableFrom: null,
  bookableTo: null,
  temporaryHold: null,
  sellsRequestedPeriod: true,
  nearestCheckIn: null,
  nearestCheckOut: null,
  ...over,
});
