import {
  AirVent,
  Anchor,
  Armchair,
  ArrowDownToLine,
  ArrowUpFromLine,
  AudioLines,
  Axe,
  Bath,
  Battery,
  BatteryCharging,
  BedDouble,
  BedSingle,
  BellRing,
  Binoculars,
  Blend,
  Blinds,
  Bluetooth,
  Box,
  BriefcaseMedical,
  Brush,
  Bug,
  Cable,
  Circle,
  Clock,
  Coffee,
  Cog,
  Compass,
  Container,
  CookingPot,
  Cylinder,
  Droplet,
  Droplets,
  Fan,
  FileText,
  FireExtinguisher,
  Fish,
  Flag,
  Flame,
  Flashlight,
  Footprints,
  Fuel,
  Gamepad2,
  Gauge,
  Glasses,
  HandGrab,
  Heater,
  KeyRound,
  Layers,
  Layers2,
  LifeBuoy,
  Lightbulb,
  Link,
  Link2,
  Lock,
  Map,
  MapPinned,
  Megaphone,
  Microwave,
  Navigation,
  Package,
  PaintBucket,
  Plug,
  PlugZap,
  Radar,
  Radio,
  RadioTower,
  Refrigerator,
  Rocket,
  RotateCw,
  Ruler,
  Sailboat,
  Sandwich,
  Satellite,
  Scissors,
  Shield,
  ShieldCheck,
  Ship,
  ShipWheel,
  Shirt,
  ShowerHead,
  Snowflake,
  Sofa,
  Speaker,
  Sun,
  Table,
  Tent,
  Thermometer,
  Toilet,
  TreePine,
  Tv,
  Umbrella,
  Usb,
  Utensils,
  UtensilsCrossed,
  WashingMachine,
  WavesArrowUp,
  Wifi,
  Wind,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * What each icon slug is drawn with until the client's own SVG set lands.
 *
 * The slug is resolved server-side (`amenityIconFor` in the db package), because by the time a
 * label reaches this component it has been translated and no English table would match it. That
 * leaves this file owning one thing only: which drawing a slug maps to. Swapping these for the
 * commissioned SVGs is a change to this map and nothing else.
 *
 * Several slugs share a component on purpose -- every anchor variant is one anchor -- for the
 * same reason the slug table folds them: a reader gains nothing from two hundred near-identical
 * marks, and a designer would have to draw them.
 */
const AMENITY_ICONS = {
  "air-conditioning": AirVent,
  anchor: Anchor,
  autopilot: Navigation,
  barbecue: Flame,
  barometer: Gauge,
  battery: Battery,
  "battery-charger": BatteryCharging,
  "bed-linen": BedDouble,
  "bilge-alarm": BellRing,
  "bilge-pump": Droplets,
  bimini: Tent,
  binoculars: Binoculars,
  blanket: Layers,
  blender: Blend,
  bluetooth: Bluetooth,
  "boat-hook": HandGrab,
  "bolt-cutter": Scissors,
  "bosun-chair": Armchair,
  "bow-thruster": Wind,
  bucket: PaintBucket,
  "chart-plotter": MapPinned,
  charts: Map,
  cleaning: Brush,
  cleat: Link2,
  clock: Clock,
  "cockpit-fridge": Refrigerator,
  "cockpit-table": Table,
  "coffee-maker": Coffee,
  compass: Compass,
  "cool-box": Box,
  curtains: Blinds,
  cushions: Sofa,
  cutlery: Utensils,
  davit: ArrowUpFromLine,
  "day-shape": Circle,
  "deck-brush": Brush,
  "deck-light": Lightbulb,
  "depth-sounder": WavesArrowUp,
  dinghy: Sailboat,
  "dinghy-pump": Wind,
  dishwasher: WashingMachine,
  documents: FileText,
  "emergency-tiller": Wrench,
  epirb: RadioTower,
  fan: Fan,
  fender: Shield,
  "fire-axe": Axe,
  "fire-extinguisher": FireExtinguisher,
  "first-aid": BriefcaseMedical,
  fishing: Fish,
  flag: Flag,
  flare: Rocket,
  flybridge: Layers2,
  "fog-horn": Megaphone,
  freezer: Snowflake,
  fridge: Refrigerator,
  "game-console": Gamepad2,
  gangway: Footprints,
  "gas-bottle": Cylinder,
  generator: Zap,
  gps: Satellite,
  "hair-dryer": Wind,
  hanger: Shirt,
  heating: Heater,
  helm: ShipWheel,
  "holding-tank": Container,
  "hot-water": Droplet,
  "ice-maker": Snowflake,
  inverter: Plug,
  "jerry-can": Fuel,
  kettle: CookingPot,
  keys: KeyRound,
  "lazy-bag": Package,
  "led-lights": Lightbulb,
  "life-jacket": ShieldCheck,
  lifebuoy: LifeBuoy,
  liferaft: Ship,
  microwave: Microwave,
  "mosquito-net": Bug,
  "navigation-lights": Lightbulb,
  oars: WavesArrowUp,
  "outboard-engine": Cog,
  "outside-shower": ShowerHead,
  oven: Flame,
  paddleboard: WavesArrowUp,
  pillow: BedSingle,
  "plotting-tools": Ruler,
  pool: WavesArrowUp,
  propeller: Fan,
  radar: Radar,
  radio: Radio,
  rope: Cable,
  safe: Lock,
  "safety-harness": Link,
  "safety-kit": BriefcaseMedical,
  sail: Sailboat,
  "saloon-table": Table,
  "shore-power": PlugZap,
  shower: ShowerHead,
  sink: Droplet,
  snorkel: Glasses,
  socket: Plug,
  "solar-panel": Sun,
  "sound-system": Speaker,
  speaker: Speaker,
  "speed-log": Gauge,
  sprayhood: Umbrella,
  stove: Flame,
  "sun-deck": Sun,
  sunshade: Umbrella,
  "swim-ladder": ArrowDownToLine,
  "swim-platform": WavesArrowUp,
  teak: TreePine,
  toaster: Sandwich,
  toilet: Toilet,
  tools: Wrench,
  torch: Flashlight,
  towel: Bath,
  tv: Tv,
  "underwater-light": Lightbulb,
  upholstery: Sofa,
  "usb-socket": Usb,
  "vhf-radio": RadioTower,
  washer: WashingMachine,
  "water-heater": Thermometer,
  "water-hose": Droplets,
  "water-maker": Droplets,
  "water-pump": Droplets,
  "water-skis": WavesArrowUp,
  "water-tank": Container,
  wifi: Wifi,
  winch: RotateCw,
  "wind-instrument": Wind,
  windlass: Anchor,
} satisfies Record<string, LucideIcon>;

/** One icon per heading, shown on the group's own band. */
const GROUP_ICONS = {
  "navigation-and-safety": Compass,
  "deck-and-cockpit": Anchor,
  "interior-and-cabins": BedDouble,
  galley: UtensilsCrossed,
  "entertainment-and-water-toys": AudioLines,
  "systems-and-power": Zap,
  other: Package,
} satisfies Record<string, LucideIcon>;

/** The group's icon stands in wherever an amenity has no drawing of its own. */
export function amenityIcon(slug: string | null, group: string): LucideIcon {
  return (slug ? lookup(AMENITY_ICONS, slug) : undefined) ?? groupIcon(group);
}

export function groupIcon(group: string): LucideIcon {
  return lookup(GROUP_ICONS, group) ?? Package;
}

function lookup(table: Record<string, LucideIcon>, key: string): LucideIcon | undefined {
  return table[key];
}
