import type { Marina } from "../types";

/*
 * Mock catalogue — goes away with the search procedure, like `sample-boats`.
 * Marinas are keyed rather than inlined per boat: several yachts share one marina,
 * and the API will return them normalised too. A couple deliberately lack a website
 * or an email so the card's "hide the missing row" path stays exercised.
 */
const MAP_THUMB = "/assets/marinas/map-thumb.jpg";

function marina(value: Omit<Marina, "mapImageUrl">): Marina {
  return { ...value, mapImageUrl: MAP_THUMB };
}

export const SAMPLE_MARINAS = {
  aciSplit: marina({
    id: "aci-split",
    name: "ACI Marina Split",
    address: "Uvala Baluni 8",
    city: "Split",
    country: "Croatia",
    phone: "+385 21 398 599",
    website: "www.aci-marinas.com",
    email: "split@aci-marinas.com",
    coordinates: { lat: 43.5015, lng: 16.434 },
  }),
  aciDubrovnik: marina({
    id: "aci-dubrovnik",
    name: "ACI Marina Dubrovnik",
    address: "Na Skali 2, 20236 Mokošica",
    city: "Dubrovnik",
    country: "Croatia",
    phone: "+385 20 455 020",
    website: "www.aci-marinas.com",
    email: "dubrovnik@aci-marinas.com",
    coordinates: { lat: 42.68, lng: 18.12 },
  }),
  mykonos: marina({
    id: "mykonos-new-port",
    name: "Mykonos New Port Marina",
    address: "Tourlos",
    city: "Mykonos",
    country: "Greece",
    phone: "+30 2289 023 990",
    website: "www.mykonosports.gr",
    coordinates: { lat: 37.46, lng: 25.33 },
  }),
  palma: marina({
    id: "rcn-palma",
    name: "Real Club Náutico de Palma",
    address: "Muelle de San Pedro 1",
    city: "Palma de Mallorca",
    country: "Spain",
    phone: "+34 971 726 848",
    website: "www.rcnp.es",
    email: "info@rcnp.es",
    coordinates: { lat: 39.564, lng: 2.632 },
  }),
  aoPo: marina({
    id: "ao-po-grand",
    name: "Ao Po Grand Marina",
    address: "42/2 Moo 5, Pa Klok, Thalang",
    city: "Phuket",
    country: "Thailand",
    phone: "+66 76 602 461",
    website: "www.aopograndmarina.com",
    email: "info@aopograndmarina.com",
    coordinates: { lat: 8.04, lng: 98.43 },
  }),
  kastela: marina({
    id: "marina-kastela",
    name: "Marina Kaštela",
    address: "Kaštel Gomilica bb",
    city: "Kaštela",
    country: "Croatia",
    phone: "+385 21 204 010",
    website: "www.marina-kastela.hr",
    email: "info@marina-kastela.hr",
    coordinates: { lat: 43.545, lng: 16.39 },
  }),
  gocek: marina({
    id: "d-marin-gocek",
    name: "D-Marin Göcek",
    address: "Göcek Mahallesi, Turgut Özal Cd. 1",
    city: "Göcek",
    country: "Türkiye",
    phone: "+90 252 645 1800",
    website: "www.d-marin.com",
    email: "gocek@d-marin.com",
    coordinates: { lat: 36.75, lng: 28.94 },
  }),
  alimos: marina({
    id: "marina-alimos",
    name: "Marina Alimos",
    address: "Leoforos Posidonos",
    city: "Athens",
    country: "Greece",
    phone: "+30 210 988 8000",
    email: "info@alimosmarina.gr",
    coordinates: { lat: 37.91, lng: 23.7 },
  }),
  nannyCay: marina({
    id: "nanny-cay",
    name: "Nanny Cay Marina",
    address: "Nanny Cay, Road Town",
    city: "Tortola",
    country: "British Virgin Islands",
    phone: "+1 284 494 2512",
    website: "www.nannycay.com",
    email: "marina@nannycay.com",
    coordinates: { lat: 18.4, lng: -64.62 },
  }),
  portisco: marina({
    id: "marina-di-portisco",
    name: "Marina di Portisco",
    address: "Località Portisco",
    city: "Sardinia",
    country: "Italy",
    phone: "+39 0789 33 561",
    website: "www.marinadiportisco.com",
    coordinates: { lat: 41.03, lng: 9.51 },
  }),
  punat: marina({
    id: "marina-punat",
    name: "Marina Punat",
    address: "Puntica 7",
    city: "Krk",
    country: "Croatia",
    phone: "+385 51 654 111",
    website: "www.marina-punat.hr",
    email: "marina@marina-punat.hr",
    coordinates: { lat: 45.02, lng: 14.63 },
  }),
  leMarin: marina({
    id: "marina-le-marin",
    name: "Marina Le Marin",
    address: "Port de Plaisance",
    city: "Le Marin",
    country: "Martinique",
    phone: "+596 596 74 83 83",
    website: "www.marinlemarin.com",
    coordinates: { lat: 14.47, lng: -60.87 },
  }),
  antibes: marina({
    id: "port-vauban",
    name: "Port Vauban",
    address: "Avenue de Verdun",
    city: "Antibes",
    country: "France",
    phone: "+33 4 92 91 60 00",
    website: "www.portvauban-antibes.fr",
    email: "contact@portvauban.net",
    coordinates: { lat: 43.586, lng: 7.128 },
  }),
  zeas: marina({
    id: "marina-zeas",
    name: "Marina Zeas",
    address: "Akti Themistokleous",
    city: "Piraeus",
    country: "Greece",
    phone: "+30 210 428 3300",
    website: "www.marinazeas.gr",
    email: "info@marinazeas.gr",
    coordinates: { lat: 37.935, lng: 23.648 },
  }),
  frapa: marina({
    id: "marina-frapa",
    name: "Marina Frapa",
    address: "Uvala Soline 1",
    city: "Rogoznica",
    country: "Croatia",
    phone: "+385 22 559 900",
    website: "www.marinafrapa.hr",
    email: "marina@marinafrapa.hr",
    coordinates: { lat: 43.53, lng: 15.97 },
  }),
  ibiza: marina({
    id: "marina-ibiza",
    name: "Marina Ibiza",
    address: "Passeig Joan Carles I 33",
    city: "Ibiza",
    country: "Spain",
    phone: "+34 971 318 040",
    website: "www.marinaibiza.com",
    email: "info@marinaibiza.com",
    coordinates: { lat: 38.91, lng: 1.44 },
  }),
} satisfies Record<string, Marina>;
