import {
  Anchor,
  Refrigerator,
  Snowflake,
  Sun,
  Tag,
  Utensils,
  Waves,
  Wifi,
  Wrench,
} from "lucide-react";

import type { BoatCardAmenity, BoatCardProps, BoatCardSpec } from "../components/boat-card";

export type SampleBoat = Omit<BoatCardProps, "className" | "priority"> & { id: string };

const PHOTO = "/assets/yachts/lagoon-42.jpg";

const photos = (count: number) => Array.from({ length: count }, () => PHOTO);

const WIFI: BoatCardAmenity = { icon: <Wifi />, label: "Free Wi-Fi" };
const SOLAR: BoatCardAmenity = { icon: <Sun />, label: "3 Sun Panels" };
const PADDLE: BoatCardAmenity = { icon: <Wrench />, label: "Free Standup Paddle" };
const AIR: BoatCardAmenity = { icon: <Snowflake />, label: "Air conditioning" };
const WATER_TOYS: BoatCardAmenity = { icon: <Waves />, label: "Water toys" };
const GALLEY: BoatCardAmenity = { icon: <Utensils />, label: "Full galley" };
const FRIDGE: BoatCardAmenity = { icon: <Refrigerator />, label: "Fridge & freezer" };
const TENDER: BoatCardAmenity = { icon: <Anchor />, label: "Tender with outboard" };

function specs(spec: {
  year: number;
  people: number;
  toilets: number;
  baths: number;
  cabins: number;
  length: string;
  mainsail?: string;
}): BoatCardSpec[] {
  return [
    { label: "Year", value: String(spec.year) },
    { label: "People", value: String(spec.people) },
    { label: "Toilets", value: String(spec.toilets) },
    { label: "Baths", value: String(spec.baths) },
    { label: "Mainsail type", value: spec.mainsail ?? "Batten mainsail" },
    { label: "Cabins", value: String(spec.cabins) },
    { label: "Length", value: spec.length },
  ];
}

export const SAMPLE_BOATS: SampleBoat[] = [
  {
    id: "lagoon-42",
    images: photos(5),
    imageAlt: "Lagoon 42 catamaran moored in Split",
    badges: [
      { label: "Best for families" },
      { label: "Best value" },
      { label: "15% OFF", icon: <Tag />, solid: true },
    ],
    location: "ACI Marina Split, Split, Croatia",
    name: "Lagoon 42",
    rating: "5.9",
    charterType: "Bareboat",
    crew: "Full crew",
    specs: specs({ year: 2016, people: 12, toilets: 2, baths: 2, cabins: 4, length: "12.8 m" }),
    amenities: [WIFI, SOLAR, PADDLE],
    stats: ["3 booked this month", "42 people viewed today"],
    start: "2026-07-07T17:00:00+02:00",
    end: "2026-07-25T22:00:00+02:00",
    timeZone: "Europe/Zagreb",
    priceLabel: "Price for 7 days",
    price: "€5,700",
    perPerson: "~ €475 for person",
    prepayment: "Booking prepayment: €1,400",
  },
  {
    id: "sunreef-60",
    images: photos(6),
    imageAlt: "Sunreef 60 luxury catamaran under sail",
    location: "ACI Marina Split, Split, Croatia",
    name: "Sunreef 60",
    rating: "5.9",
    charterType: "Catamaran",
    crew: "Full crew",
    specs: specs({
      year: 2021,
      people: 10,
      toilets: 5,
      baths: 5,
      cabins: 5,
      length: "18.3 m",
      mainsail: "Full batten mainsail",
    }),
    amenities: [WIFI, AIR, WATER_TOYS],
    stats: ["1 booked this month", "88 people viewed today"],
    start: "2026-07-07T17:00:00+02:00",
    end: "2026-07-25T22:00:00+02:00",
    timeZone: "Europe/Zagreb",
    priceLabel: "Price for 7 days",
    price: "€18,500",
    perPerson: "€1,850 for person",
    prepayment: "Booking prepayment: €4,600",
  },
  {
    id: "beneteau-oceanis-46",
    images: photos(4),
    imageAlt: "Beneteau Oceanis 46.1 sailing off the Dalmatian coast",
    location: "ACI Marina Split, Split, Croatia",
    name: "Beneteau Oceanis 46.1",
    rating: "5.9",
    charterType: "Bareboat Sailing Yacht",
    crew: "Full crew",
    specs: specs({ year: 2019, people: 10, toilets: 3, baths: 2, cabins: 4, length: "14.6 m" }),
    amenities: [WIFI, SOLAR, PADDLE],
    stats: ["5 booked this month", "37 people viewed today"],
    start: "2026-07-07T17:00:00+02:00",
    end: "2026-07-25T22:00:00+02:00",
    timeZone: "Europe/Zagreb",
    priceLabel: "Price for 7 days",
    price: "€4,200",
    perPerson: "~ €420 for person",
    prepayment: "Booking prepayment: €1,050",
  },
  {
    id: "lagoon-52f",
    images: photos(5),
    imageAlt: "Lagoon 52 F at anchor near Dubrovnik",
    badges: [{ label: "Best value" }, { label: "15% OFF", icon: <Tag />, solid: true }],
    location: "ACI Marina Dubrovnik, Dubrovnik, Croatia",
    name: "Lagoon 52 F",
    rating: "5.9",
    charterType: "Bareboat",
    crew: "Full crew",
    specs: specs({ year: 2020, people: 12, toilets: 4, baths: 4, cabins: 6, length: "15.8 m" }),
    amenities: [WIFI, AIR, TENDER],
    stats: ["4 booked this month", "61 people viewed today"],
    start: "2026-07-07T17:00:00+02:00",
    end: "2026-07-25T22:00:00+02:00",
    timeZone: "Europe/Zagreb",
    priceLabel: "Price for 7 days",
    price: "€15,900",
    perPerson: "~ €1,325 for person",
    prepayment: "Booking prepayment: €3,900",
  },
  {
    id: "bavaria-c38",
    images: photos(4),
    imageAlt: "Bavaria C38 leaving Mykonos harbour",
    badges: [{ label: "Best for families" }, { label: "15% OFF", icon: <Tag />, solid: true }],
    location: "Mykonos New Port Marina, Mykonos, Greece",
    name: "Bavaria C38",
    rating: "5.9",
    charterType: "Bareboat",
    crew: "Full crew",
    specs: specs({ year: 2022, people: 8, toilets: 2, baths: 1, cabins: 3, length: "11.7 m" }),
    amenities: [WIFI, SOLAR, GALLEY],
    stats: ["2 booked this month", "29 people viewed today"],
    start: "2026-07-07T17:00:00+03:00",
    end: "2026-07-25T22:00:00+03:00",
    timeZone: "Europe/Athens",
    priceLabel: "Price for 7 days",
    price: "€7,800",
    perPerson: "~ €975 for person",
    prepayment: "Booking prepayment: €1,950",
  },
  {
    id: "dufour-470",
    images: photos(3),
    imageAlt: "Dufour 470 berthed in Palma de Mallorca",
    location: "Real Club Náutico de Palma, Palma de Mallorca, Spain",
    name: "Dufour 470",
    rating: "5.9",
    charterType: "Bareboat",
    crew: "Full crew",
    specs: specs({ year: 2021, people: 10, toilets: 3, baths: 2, cabins: 4, length: "14.2 m" }),
    amenities: [WIFI, AIR, PADDLE],
    stats: ["3 booked this month", "18 people viewed today"],
    start: "2026-07-07T17:00:00+02:00",
    end: "2026-07-25T22:00:00+02:00",
    timeZone: "Europe/Madrid",
    priceLabel: "Price for 7 days",
    price: "€6,900",
    perPerson: "~ €690 for person",
    prepayment: "Booking prepayment: €1,700",
  },
  {
    id: "fountaine-pajot-elba-45",
    images: photos(6),
    imageAlt: "Fountaine Pajot Elba 45 in the Andaman Sea",
    badges: [{ label: "Best for families" }, { label: "Best value" }],
    location: "Ao Po Grand Marina, Phuket, Thailand",
    name: "Fountaine Pajot Elba 45",
    rating: "5.9",
    charterType: "Bareboat",
    crew: "Full crew",
    specs: specs({ year: 2019, people: 12, toilets: 4, baths: 4, cabins: 4, length: "13.6 m" }),
    amenities: [WIFI, AIR, WATER_TOYS],
    stats: ["6 booked this month", "54 people viewed today"],
    start: "2026-07-07T17:00:00+07:00",
    end: "2026-07-25T22:00:00+07:00",
    timeZone: "Asia/Bangkok",
    priceLabel: "Price for 7 days",
    price: "€5,700",
    perPerson: "~ €475 for person",
    prepayment: "Booking prepayment: €1,400",
  },
  {
    id: "sun-odyssey-410",
    images: photos(4),
    imageAlt: "Jeanneau Sun Odyssey 410 in Marina Kaštela",
    location: "Marina Kaštela, Kaštela, Croatia",
    name: "Sun Odyssey 410",
    rating: "5.7",
    charterType: "Bareboat",
    crew: "Skipper optional",
    specs: specs({ year: 2018, people: 8, toilets: 2, baths: 1, cabins: 3, length: "12.3 m" }),
    amenities: [WIFI, SOLAR, GALLEY],
    stats: ["2 booked this month", "23 people viewed today"],
    start: "2026-07-07T17:00:00+02:00",
    end: "2026-07-25T22:00:00+02:00",
    timeZone: "Europe/Zagreb",
    priceLabel: "Price for 7 days",
    price: "€3,900",
    perPerson: "~ €490 for person",
    prepayment: "Booking prepayment: €980",
  },
  {
    id: "hanse-508",
    images: photos(5),
    imageAlt: "Hanse 508 moored in Göcek",
    badges: [{ label: "20% OFF", icon: <Tag />, solid: true }],
    location: "D-Marin Göcek, Göcek, Türkiye",
    name: "Hanse 508",
    rating: "5.8",
    charterType: "Bareboat Sailing Yacht",
    crew: "Full crew",
    specs: specs({
      year: 2020,
      people: 10,
      toilets: 3,
      baths: 3,
      cabins: 5,
      length: "15.4 m",
      mainsail: "Full batten mainsail",
    }),
    amenities: [WIFI, AIR, TENDER],
    stats: ["4 booked this month", "46 people viewed today"],
    start: "2026-07-07T17:00:00+03:00",
    end: "2026-07-25T22:00:00+03:00",
    timeZone: "Europe/Istanbul",
    priceLabel: "Price for 7 days",
    price: "€8,400",
    perPerson: "~ €840 for person",
    prepayment: "Booking prepayment: €2,100",
  },
  {
    id: "bali-46",
    images: photos(5),
    imageAlt: "Bali 4.6 catamaran leaving Alimos marina",
    badges: [{ label: "Best for families" }],
    location: "Marina Alimos, Athens, Greece",
    name: "Bali 4.6",
    rating: "5.9",
    charterType: "Catamaran",
    crew: "Full crew",
    specs: specs({ year: 2022, people: 12, toilets: 4, baths: 4, cabins: 5, length: "14.0 m" }),
    amenities: [WIFI, AIR, WATER_TOYS],
    stats: ["7 booked this month", "73 people viewed today"],
    start: "2026-07-07T17:00:00+03:00",
    end: "2026-07-25T22:00:00+03:00",
    timeZone: "Europe/Athens",
    priceLabel: "Price for 7 days",
    price: "€11,200",
    perPerson: "~ €930 for person",
    prepayment: "Booking prepayment: €2,800",
  },
  {
    id: "lagoon-46",
    images: photos(6),
    imageAlt: "Lagoon 46 anchored off Tortola",
    badges: [{ label: "Best value" }],
    location: "Nanny Cay Marina, Tortola, British Virgin Islands",
    name: "Lagoon 46",
    rating: "5.9",
    charterType: "Bareboat",
    crew: "Full crew",
    specs: specs({ year: 2021, people: 12, toilets: 4, baths: 4, cabins: 4, length: "13.9 m" }),
    amenities: [WIFI, AIR, PADDLE],
    stats: ["5 booked this month", "64 people viewed today"],
    start: "2026-07-07T17:00:00-04:00",
    end: "2026-07-25T22:00:00-04:00",
    timeZone: "America/Tortola",
    priceLabel: "Price for 7 days",
    price: "€13,600",
    perPerson: "~ €1,130 for person",
    prepayment: "Booking prepayment: €3,400",
  },
  {
    id: "oceanis-51",
    images: photos(4),
    imageAlt: "Beneteau Oceanis 51.1 off the Sardinian coast",
    location: "Marina di Portisco, Sardinia, Italy",
    name: "Beneteau Oceanis 51.1",
    rating: "5.8",
    charterType: "Bareboat Sailing Yacht",
    crew: "Skipper optional",
    specs: specs({ year: 2020, people: 10, toilets: 3, baths: 3, cabins: 5, length: "15.9 m" }),
    amenities: [WIFI, FRIDGE, GALLEY],
    stats: ["3 booked this month", "31 people viewed today"],
    start: "2026-07-07T17:00:00+02:00",
    end: "2026-07-25T22:00:00+02:00",
    timeZone: "Europe/Rome",
    priceLabel: "Price for 7 days",
    price: "€9,300",
    perPerson: "~ €930 for person",
    prepayment: "Booking prepayment: €2,300",
  },
  {
    id: "elan-impression-45",
    images: photos(3),
    imageAlt: "Elan Impression 45.1 in Marina Punat",
    badges: [{ label: "Best value" }, { label: "15% OFF", icon: <Tag />, solid: true }],
    location: "Marina Punat, Krk, Croatia",
    name: "Elan Impression 45.1",
    rating: "5.6",
    charterType: "Bareboat",
    crew: "Skipper optional",
    specs: specs({ year: 2017, people: 10, toilets: 3, baths: 2, cabins: 4, length: "13.9 m" }),
    amenities: [WIFI, SOLAR, GALLEY],
    stats: ["2 booked this month", "26 people viewed today"],
    start: "2026-07-07T17:00:00+02:00",
    end: "2026-07-25T22:00:00+02:00",
    timeZone: "Europe/Zagreb",
    priceLabel: "Price for 7 days",
    price: "€4,600",
    perPerson: "~ €460 for person",
    prepayment: "Booking prepayment: €1,150",
  },
  {
    id: "astrea-42",
    images: photos(5),
    imageAlt: "Fountaine Pajot Astréa 42 in Le Marin",
    location: "Marina Le Marin, Le Marin, Martinique",
    name: "Fountaine Pajot Astréa 42",
    rating: "5.8",
    charterType: "Catamaran",
    crew: "Full crew",
    specs: specs({ year: 2019, people: 10, toilets: 4, baths: 4, cabins: 4, length: "12.6 m" }),
    amenities: [WIFI, AIR, TENDER],
    stats: ["4 booked this month", "39 people viewed today"],
    start: "2026-07-07T17:00:00-04:00",
    end: "2026-07-25T22:00:00-04:00",
    timeZone: "America/Martinique",
    priceLabel: "Price for 7 days",
    price: "€10,800",
    perPerson: "~ €1,080 for person",
    prepayment: "Booking prepayment: €2,700",
  },
  {
    id: "dufour-530",
    images: photos(4),
    imageAlt: "Dufour 530 berthed at Port Vauban, Antibes",
    badges: [{ label: "New" }],
    location: "Port Vauban, Antibes, France",
    name: "Dufour 530",
    rating: "5.9",
    charterType: "Bareboat Sailing Yacht",
    crew: "Full crew",
    specs: specs({
      year: 2023,
      people: 10,
      toilets: 3,
      baths: 3,
      cabins: 5,
      length: "16.2 m",
      mainsail: "Full batten mainsail",
    }),
    amenities: [WIFI, AIR, WATER_TOYS],
    stats: ["1 booked this month", "57 people viewed today"],
    start: "2026-07-07T17:00:00+02:00",
    end: "2026-07-25T22:00:00+02:00",
    timeZone: "Europe/Paris",
    priceLabel: "Price for 7 days",
    price: "€12,500",
    perPerson: "~ €1,250 for person",
    prepayment: "Booking prepayment: €3,100",
  },
  {
    id: "sun-odyssey-490",
    images: photos(4),
    imageAlt: "Sun Odyssey 490 in Marina Zeas, Piraeus",
    location: "Marina Zeas, Piraeus, Greece",
    name: "Sun Odyssey 490",
    rating: "5.7",
    charterType: "Bareboat",
    crew: "Skipper optional",
    specs: specs({ year: 2018, people: 10, toilets: 3, baths: 2, cabins: 5, length: "14.7 m" }),
    amenities: [WIFI, SOLAR, PADDLE],
    stats: ["3 booked this month", "22 people viewed today"],
    start: "2026-07-07T17:00:00+03:00",
    end: "2026-07-25T22:00:00+03:00",
    timeZone: "Europe/Athens",
    priceLabel: "Price for 7 days",
    price: "€6,100",
    perPerson: "~ €610 for person",
    prepayment: "Booking prepayment: €1,500",
  },
  {
    id: "nautitech-46",
    images: photos(5),
    imageAlt: "Nautitech 46 Open sailing near Rogoznica",
    badges: [{ label: "Best for families" }, { label: "Best value" }],
    location: "Marina Frapa, Rogoznica, Croatia",
    name: "Nautitech 46 Open",
    rating: "5.8",
    charterType: "Catamaran",
    crew: "Full crew",
    specs: specs({ year: 2020, people: 12, toilets: 4, baths: 4, cabins: 4, length: "13.8 m" }),
    amenities: [WIFI, AIR, FRIDGE],
    stats: ["5 booked this month", "48 people viewed today"],
    start: "2026-07-07T17:00:00+02:00",
    end: "2026-07-25T22:00:00+02:00",
    timeZone: "Europe/Zagreb",
    priceLabel: "Price for 7 days",
    price: "€9,900",
    perPerson: "~ €825 for person",
    prepayment: "Booking prepayment: €2,400",
  },
  {
    id: "oceanis-yacht-62",
    images: photos(6),
    imageAlt: "Oceanis Yacht 62 leaving Marina Ibiza",
    badges: [{ label: "20% OFF", icon: <Tag />, solid: true }],
    location: "Marina Ibiza, Ibiza, Spain",
    name: "Oceanis Yacht 62",
    rating: "5.9",
    charterType: "Bareboat Sailing Yacht",
    crew: "Full crew",
    specs: specs({
      year: 2022,
      people: 8,
      toilets: 4,
      baths: 4,
      cabins: 4,
      length: "18.9 m",
      mainsail: "Full batten mainsail",
    }),
    amenities: [WIFI, AIR, TENDER],
    stats: ["2 booked this month", "95 people viewed today"],
    start: "2026-07-07T17:00:00+02:00",
    end: "2026-07-25T22:00:00+02:00",
    timeZone: "Europe/Madrid",
    priceLabel: "Price for 7 days",
    price: "€21,400",
    perPerson: "~ €2,675 for person",
    prepayment: "Booking prepayment: €5,300",
  },
];

export const RESULTS_TOTAL = 320;
export const RESULTS_PER_PAGE = 7;

/** The deck is shorter than the pretended total, so it cycles — ids stay unique per page. */
export function getBoatsPage(page: number): SampleBoat[] {
  const offset = (page - 1) * RESULTS_PER_PAGE;
  const size = Math.min(page * RESULTS_PER_PAGE, RESULTS_TOTAL) - offset;
  return Array.from({ length: Math.max(size, 0) }, (_, index) => {
    const boat = SAMPLE_BOATS[(offset + index) % SAMPLE_BOATS.length] as SampleBoat;
    return { ...boat, id: `${boat.id}-p${page}` };
  });
}
